#!/usr/bin/env python3
import sys
import fiona
from alive_progress import alive_bar
import os

def write_source(sink, source):
  for f in source:
    sink.write(f)
    yield


def main(argv=sys.argv[1:]):
  if (len(argv) < 2):
    print "Usage: gdb_dump [input_gdb_path] [output_directory]"
  for layername in fiona.listlayers('src/fsm_seasketch.gdb'):
    with fiona.open(argv[0], "r", layer=layername) as src:
      source_driver = src.driver
      source_schema = src.schema
      source_crs = src.crs
      path = os.path.join(argv[1], layername + ".fgb")
      print("Writing " + path)
      with fiona.open(
        path,
        'w',
        driver="FlatGeobuf",
        crs=source_crs,
        schema=source_schema) as sink:
          with alive_bar(len(src)) as bar:
            for i in write_source(sink, src):
              bar()

if __name__ == '__main__':
  sys.exit(main(sys.argv[1:]))